version: '3.7'

services:
 lbs_app:
  env_file: .env
  build:
   args:
    user: ${USER}
    uid: ${UID}
   context: ./
   dockerfile: Dockerfile
  image: lbs
  container_name: lbs-app
  restart: unless-stopped
  working_dir: /usr/share/nginx/html
  volumes:
    - ${WORK_DIR_SRC}:/usr/share/nginx/html
  networks:
    - lbs

 lbs_db:
  image: mariadb
  container_name: lbs-db
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: lbsdb
    MYSQL_ROOT_PASSWORD: 123123
    MYSQL_PASSWORD: 123123
    MYSQL_USER: root
  volumes:
  - lbsdata:/var/lib/mysq
  networks:
  - lbs

 nginx_lbs:
  image: nginx
  env_file: .env
  volumes:
  - ${WORK_DIR_SRC}:/usr/share/nginx/html
  - ${WORK_DIR}:/etc/nginx/conf.d
  ports:
  -  "8019:80"
  networks:
  - lbs

networks:
  lbs:
    driver: bridge

volumes:
 lbsdata:
   name: lbsdata
   external: true
