version: '3.7'

services:
 lbs_app:
  build:
   args:
    user: germanmdd
    uid: 1001
   context: ./
   dockerfile: Dockerfile
  image: lbs
  container_name: lbs-app
  restart: unless-stopped
  working_dir: /usr/share/nginx/html
  volumes:
    - /media/psf/Home/www/lbs/src:/usr/share/nginx/html
  networks:
    - lbs

 lbs_db:
  image: mariadb
  container_name: lbs-db
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: lbsdb
    MYSQL_ROOT_PASSWORD: 123123
    MYSQL_PASSWORD: 123123
    MYSQL_USER: root
  volumes:
  - lbsdata:/var/lib/mysq
  networks:
  - lbs

 nginx_lbs:
  image: nginx
  volumes:
  - /media/psf/Home/www/lbs/src:/usr/share/nginx/html
  - /media/psf/Home/www/lbs:/etc/nginx/conf.d
  ports:
  -  "8019:80"
  networks:
  - lbs

networks:
  lbs:
    driver: bridge

volumes:
 lbsdata:
   name: lbsdata
   external: true
